export const CITIZEN_SERVICE_GROUPS = [
    { id: 'applications', label: 'আবেদন ও সনদ' },
    { id: 'welfare', label: 'ভাতা ও সহায়তা' },
    { id: 'safety', label: 'অভিযোগ ও জরুরি' },
    { id: 'family', label: 'পরিবার ও নথি' },
    { id: 'livelihood', label: 'কৃষি ও কর্মসংস্থান' },
    { id: 'health-education', label: 'স্বাস্থ্য ও শিক্ষা' },
    { id: 'payments', label: 'ফি ও পেমেন্ট' },
];

export const CITIZEN_SERVICES = [
    {
        id: 'certificates', group: 'applications', icon: 'FileBadge', title: 'নাগরিক আবেদন ও সনদ',
        summary: 'নাগরিকত্ব, ওয়ারিশ, আয়, চারিত্রিক, জন্ম ও মৃত্যু সনদের প্রস্তুতি ও tracking।',
        audience: 'যাদের ইউনিয়ন পরিষদ বা স্থানীয় অফিসের সনদ ও প্রত্যয়ন প্রয়োজন।',
        documents: ['জাতীয় পরিচয়পত্র/জন্মনিবন্ধন', 'সচল মোবাইল নম্বর', 'ঠিকানা ও পরিবারের তথ্য', 'সেবাভেদে সহায়ক প্রমাণপত্র'],
        steps: ['প্রয়োজনীয় সনদের ধরন বাছাই করুন', 'তথ্য ও কাগজপত্র প্রস্তুত করুন', 'Citizen Center-এ request দিন', 'Tracking ID দিয়ে অবস্থা দেখুন'],
        primaryHref: '/citizen#life-support', primaryLabel: 'সনদ সহায়তা নিন', secondaryHref: '/track', secondaryLabel: 'আবেদন দেখুন',
        note: 'চূড়ান্ত সনদ সংশ্লিষ্ট কর্তৃপক্ষ যাচাই ও অনুমোদন করে।',
    },
    {
        id: 'benefits', group: 'welfare', icon: 'HandHeart', title: 'সরকারি ভাতা ও সহায়তা',
        summary: 'বয়স্ক, বিধবা, মাতৃত্বকালীন ও প্রতিবন্ধী ভাতার আবেদন প্রস্তুত করুন।',
        audience: 'সরকারি সামাজিক সুরক্ষা কর্মসূচির সম্ভাব্য আবেদনকারী।',
        documents: ['জাতীয় পরিচয়পত্র/জন্মনিবন্ধন', 'নাগরিকত্ব/বাসিন্দা সনদ', 'প্রযোজ্য যোগ্যতার প্রমাণ', 'ব্যাংক বা মোবাইল আর্থিক হিসাব'],
        steps: ['ভাতার ধরন নির্বাচন করুন', 'প্রাথমিক যোগ্যতা মিলিয়ে নিন', 'Document checklist সম্পন্ন করুন', 'সারাংশ Print/PDF করে নির্ধারিত অফিসে জমা দিন'],
        primaryHref: '/benefits/apply', primaryLabel: 'ভাতা আবেদন প্রস্তুত করুন', secondaryHref: '/citizen#life-support', secondaryLabel: 'সহায়তা চান',
        note: 'DigiGram আবেদন প্রস্তুত করে; নির্বাচন ও অনুমোদন সরকারি কর্তৃপক্ষের।',
    },
    {
        id: 'complaints', group: 'safety', icon: 'MapPinned', title: 'স্থানীয় অভিযোগ ও সমস্যা',
        summary: 'রাস্তা, ড্রেন, পানি, বিদ্যুৎ, বর্জ্য বা সড়কবাতির সমস্যা report ও track করুন।',
        audience: 'নিজ এলাকার নাগরিক সমস্যা কর্তৃপক্ষকে জানাতে চান এমন ব্যক্তি।',
        documents: ['সমস্যার পরিষ্কার বিবরণ', 'সঠিক স্থান/ঠিকানা', 'ছবি থাকলে সহায়ক হবে', 'যোগাযোগের মোবাইল নম্বর'],
        steps: ['সমস্যার ধরন ও অগ্রাধিকার বাছাই করুন', 'স্থান এবং বিবরণ দিন', 'অভিযোগ জমা দিন', 'Tracking/OTP inbox-এ অগ্রগতি দেখুন'],
        primaryHref: '/citizen#complaint', primaryLabel: 'অভিযোগ করুন', secondaryHref: '/track?type=complaint', secondaryLabel: 'অভিযোগের অবস্থা',
        note: 'তাৎক্ষণিক বিপদ বা অপরাধে online অভিযোগের অপেক্ষা না করে ৯৯৯-এ কল করুন।',
    },
    {
        id: 'emergency', group: 'safety', icon: 'Siren', title: 'জরুরি সহায়তা কেন্দ্র',
        summary: 'রক্ত, অ্যাম্বুলেন্স, হাসপাতাল, ফায়ার সার্ভিস, থানা ও দুর্যোগ সহায়তা।',
        audience: 'জরুরি স্বাস্থ্য, নিরাপত্তা বা দুর্যোগ সহায়তা প্রয়োজন এমন সবাই।',
        documents: ['জরুরি অবস্থার সংক্ষিপ্ত বিবরণ', 'সঠিক বর্তমান স্থান', 'যোগাযোগ নম্বর', 'রক্তের ক্ষেত্রে group ও হাসপাতাল'],
        steps: ['জীবনঝুঁকি হলে প্রথমে ৯৯৯-এ কল করুন', 'নিকটস্থ সেবা/হাসপাতালের সঙ্গে যোগাযোগ করুন', 'প্রয়োজনে DigiGram-এ রক্ত বা follow-up request দিন'],
        primaryHref: '/services/emergency', primaryLabel: 'জরুরি নম্বর দেখুন', secondaryHref: '/citizen#blood', secondaryLabel: 'রক্তের সাহায্য চান',
        note: 'DigiGram জরুরি সেবার বিকল্প নয়; জীবনঝুঁকিতে ৯৯৯ ব্যবহার করুন।',
    },
    {
        id: 'documents', group: 'family', icon: 'FolderLock', title: 'পরিবার ও Document Locker',
        summary: 'পরিবারের পরিচয়, সনদ ও গুরুত্বপূর্ণ কাগজ নিরাপদ household profile-এ রাখুন।',
        audience: 'পরিবারের সদস্য ও প্রয়োজনীয় কাগজপত্র এক জায়গায় পরিচালনা করতে চান যারা।',
        documents: ['Household ID বা QR', 'অনুমোদিত locker PIN', 'সমর্থিত document file', 'সদস্যের সঠিক পরিচয়'],
        steps: ['Citizen Center থেকে Home QR খুলুন', 'অনুমোদিত PIN দিয়ে locker access নিন', 'সদস্য অনুযায়ী document যোগ করুন', 'প্রয়োজনে expiry/update যাচাই করুন'],
        primaryHref: '/citizen#apply', primaryLabel: 'Household profile খুলুন', secondaryHref: '/area', secondaryLabel: 'নিজ এলাকা বাছাই',
        note: 'গোপন নথি public link বা অপরিচিত ব্যক্তির সঙ্গে share করবেন না।',
    },
    {
        id: 'farmers', group: 'livelihood', icon: 'Sprout', title: 'কৃষক সহায়তা',
        summary: 'বাজারদর, ফসলের সমস্যা, সার-বীজ, কৃষি পরামর্শ ও কর্মকর্তা follow-up।',
        audience: 'কৃষক, কৃষিশ্রমিক ও স্থানীয় কৃষিপণ্য ব্যবসায়ী।',
        documents: ['ফসল/সমস্যার নাম', 'জমি বা এলাকার অবস্থান', 'রোগের ছবি থাকলে দিন', 'যোগাযোগ নম্বর'],
        steps: ['আজকের বাজারদর দেখুন', 'সমস্যা ও ফসলের তথ্য লিখুন', 'কৃষক সহায়তা request দিন', 'কর্মকর্তার follow-up/নোটিশ দেখুন'],
        primaryHref: '/services/market', primaryLabel: 'বাজারদর দেখুন', secondaryHref: '/citizen#life-support', secondaryLabel: 'কৃষি সহায়তা চান',
        note: 'কীটনাশক বা চিকিৎসা ব্যবহারের আগে অনুমোদিত কৃষি কর্মকর্তার পরামর্শ নিন।',
    },
    {
        id: 'jobs', group: 'livelihood', icon: 'BriefcaseBusiness', title: 'কর্মসংস্থান ও প্রশিক্ষণ',
        summary: 'কাজের চাহিদা, স্থানীয় দক্ষ কর্মী, যুব প্রশিক্ষণ ও skill support request।',
        audience: 'চাকরি/কাজ খুঁজছেন, দক্ষতা শিখতে চান বা কর্মী প্রয়োজন এমন ব্যক্তি।',
        documents: ['নাম ও যোগাযোগ', 'দক্ষতা/অভিজ্ঞতার সংক্ষিপ্ত তথ্য', 'কাজের এলাকা', 'প্রশিক্ষণের আগ্রহ'],
        steps: ['কাজ বা প্রশিক্ষণের ধরন লিখুন', 'নিজ এলাকা ও দক্ষতা দিন', 'Jobs/Skills request জমা দিন', 'OTP inbox-এ follow-up দেখুন'],
        primaryHref: '/citizen#life-support', primaryLabel: 'কাজ/প্রশিক্ষণ request', secondaryHref: '/business', secondaryLabel: 'স্থানীয় ব্যবসা দেখুন',
        note: 'চাকরির নামে অগ্রিম টাকা, OTP বা গোপন আর্থিক তথ্য দেবেন না।',
    },
    {
        id: 'health', group: 'health-education', icon: 'HeartPulse', title: 'স্বাস্থ্য, মা ও শিশু',
        summary: 'ক্লিনিক appointment, checkup, টিকা ও মা-শিশুর follow-up সহায়তা।',
        audience: 'পরিবারের স্বাস্থ্যসেবা, গর্ভকালীন বা শিশুর follow-up প্রয়োজন এমন নাগরিক।',
        documents: ['রোগী/সেবাগ্রহীতার নাম ও বয়স', 'মোবাইল নম্বর', 'পূর্বের prescription/কার্ড থাকলে', 'পছন্দের তারিখ ও এলাকা'],
        steps: ['নিকটস্থ clinic/সেবা খুঁজুন', 'Appointment বা health request দিন', 'তারিখ ও প্রয়োজন লিখুন', 'SMS/OTP inbox-এ update দেখুন'],
        primaryHref: '/services/e-clinic', primaryLabel: 'ক্লিনিক সেবা', secondaryHref: '/citizen#appointment', secondaryLabel: 'Appointment নিন',
        note: 'জরুরি বা গুরুতর অসুস্থতায় online request-এর অপেক্ষা করবেন না।',
    },
    {
        id: 'education', group: 'health-education', icon: 'GraduationCap', title: 'শিক্ষা ও উপবৃত্তি সহায়তা',
        summary: 'স্কুল খোঁজা, ভর্তি, উপস্থিতি, ফলাফল, homework ও উপবৃত্তি প্রস্তুতি।',
        audience: 'শিক্ষার্থী, অভিভাবক, শিক্ষক ও শিক্ষা প্রতিষ্ঠান।',
        documents: ['শিক্ষার্থীর জন্মনিবন্ধন', 'অভিভাবকের পরিচয় ও যোগাযোগ', 'পূর্বের শ্রেণির তথ্য', 'প্রযোজ্য ক্ষেত্রে আয়/যোগ্যতার প্রমাণ'],
        steps: ['প্রতিষ্ঠান খুঁজে portal খুলুন', 'ভর্তি/guardian নির্দেশনা দেখুন', 'অনুমোদিত login-এ progress দেখুন', 'উপবৃত্তির জন্য সহায়তা request দিন'],
        primaryHref: '/services/school', primaryLabel: 'শিক্ষা প্রতিষ্ঠান খুঁজুন', secondaryHref: '/citizen#life-support', secondaryLabel: 'উপবৃত্তি সহায়তা',
        note: 'শিক্ষার্থীর ব্যক্তিগত ফলাফল ও তথ্য শুধু অনুমোদিত access-এ দেখা উচিত।',
    },
    {
        id: 'fees', group: 'payments', icon: 'ReceiptText', title: 'সরকারি ফি ও পেমেন্ট',
        summary: 'সেবার ফি, payment request, digital receipt এবং payment status যাচাই।',
        audience: 'স্থানীয় সেবা, কর বা নির্ধারিত fee পরিশোধ ও receipt রাখতে চান যারা।',
        documents: ['সেবা/বিলের reference', 'সচল মোবাইল নম্বর', 'প্রদেয় অর্থ যাচাই', 'Payment receipt/transaction reference'],
        steps: ['সেবা ও সরকারি fee যাচাই করুন', 'Payment Center-এ reference দিন', 'অনুমোদিত মাধ্যমে অর্থ দিন', 'Receipt সংরক্ষণ ও status track করুন'],
        primaryHref: '/pay', primaryLabel: 'Payment Center', secondaryHref: '/track?type=payment', secondaryLabel: 'Payment status',
        note: 'Receipt ছাড়া অতিরিক্ত অর্থ দেবেন না; সন্দেহ হলে অভিযোগ করুন।',
    },
];

export function getCitizenService(serviceId) {
    return CITIZEN_SERVICES.find((service) => service.id === serviceId) || null;
}
