export const INSTITUTION_DESIGN_PROFILES = {
    primary_school: {
        eyebrow: 'প্রাইমারি স্কুল',
        heroLine: 'শিশুর শেখা, উপস্থিতি ও অগ্রগতি একসাথে',
        accent: 'sky',
        surface: 'from-sky-50 via-white to-emerald-50',
        badge: 'bg-sky-100 text-sky-700',
        button: 'bg-sky-600 hover:bg-sky-700',
        iconWrap: 'bg-sky-100 text-sky-700',
        primaryColor: '#0284c7',
        fontFamily: 'hind_siliguri',
        defaultTemplate: 'modern',
        websitePatternClass: 'border-sky-200/70 bg-sky-50/80',
        websiteFeatureClass: 'bg-sky-50 text-sky-950',
        websiteAccentClass: 'text-sky-700',
        websiteProofLabel: 'Foundational care'
    },
    high_school: {
        eyebrow: 'হাই স্কুল',
        heroLine: 'শৃঙ্খলা, ফলাফল ও ভবিষ্যৎ প্রস্তুতির ডিজিটাল কেন্দ্র',
        accent: 'teal',
        surface: 'from-teal-50 via-white to-cyan-50',
        badge: 'bg-teal-100 text-teal-700',
        button: 'bg-teal-600 hover:bg-teal-700',
        iconWrap: 'bg-teal-100 text-teal-700',
        primaryColor: '#0f766e',
        fontFamily: 'hind_siliguri',
        defaultTemplate: 'dark_school',
        websitePatternClass: 'border-cyan-300/20 bg-cyan-200/[0.06]',
        websiteFeatureClass: 'bg-cyan-300/[0.08] text-white',
        websiteAccentClass: 'text-cyan-200',
        websiteProofLabel: 'School command center'
    },
    college: {
        eyebrow: 'কলেজ',
        heroLine: 'বিষয়ভিত্তিক শিক্ষা, ফলাফল ও উচ্চশিক্ষা ট্র্যাকিং',
        accent: 'indigo',
        surface: 'from-indigo-50 via-white to-slate-50',
        badge: 'bg-indigo-100 text-indigo-700',
        button: 'bg-indigo-600 hover:bg-indigo-700',
        iconWrap: 'bg-indigo-100 text-indigo-700',
        primaryColor: '#4338ca',
        fontFamily: 'hind_siliguri',
        defaultTemplate: 'dark_college',
        websitePatternClass: 'border-blue-300/20 bg-blue-200/[0.06]',
        websiteFeatureClass: 'bg-blue-300/[0.08] text-white',
        websiteAccentClass: 'text-cyan-200',
        websiteProofLabel: 'Higher study track'
    },
    alim_madrasa: {
        eyebrow: 'আলিম মাদ্রাসা',
        heroLine: 'দ্বীনি শিক্ষা ও আধুনিক ব্যবস্থাপনার সমন্বয়',
        accent: 'emerald',
        surface: 'from-emerald-50 via-white to-lime-50',
        badge: 'bg-emerald-100 text-emerald-700',
        button: 'bg-emerald-600 hover:bg-emerald-700',
        iconWrap: 'bg-emerald-100 text-emerald-700',
        primaryColor: '#059669',
        fontFamily: 'hind_siliguri',
        defaultTemplate: 'dark_madrasa',
        websitePatternClass: 'border-emerald-300/20 bg-emerald-200/[0.06]',
        websiteFeatureClass: 'bg-emerald-300/[0.08] text-white',
        websiteAccentClass: 'text-emerald-200',
        websiteProofLabel: 'Deen and academics'
    },
    dakhil_madrasa: {
        eyebrow: 'দাখিল মাদ্রাসা',
        heroLine: 'ইবতেদায়ি থেকে দাখিল পর্যন্ত দ্বীনি ও সাধারণ শিক্ষার সমন্বিত পথচলা',
        accent: 'emerald',
        surface: 'from-emerald-50 via-white to-lime-50',
        badge: 'bg-emerald-100 text-emerald-700',
        button: 'bg-emerald-600 hover:bg-emerald-700',
        iconWrap: 'bg-emerald-100 text-emerald-700',
        primaryColor: '#047857',
        fontFamily: 'hind_siliguri',
        defaultTemplate: 'dark_madrasa',
        websitePatternClass: 'border-emerald-300/20 bg-emerald-200/[0.06]',
        websiteFeatureClass: 'bg-emerald-300/[0.08] text-white',
        websiteAccentClass: 'text-emerald-200',
        websiteProofLabel: 'Deen and academics'
    },
    kindergarten: {
        eyebrow: 'কিন্ডারগার্টেন',
        heroLine: 'আনন্দময় শেখা, নিরাপদ যত্ন ও অভিভাবক সংযোগ',
        accent: 'rose',
        surface: 'from-rose-50 via-white to-amber-50',
        badge: 'bg-rose-100 text-rose-700',
        button: 'bg-rose-600 hover:bg-rose-700',
        iconWrap: 'bg-rose-100 text-rose-700',
        primaryColor: '#e11d48',
        fontFamily: 'hind_siliguri',
        defaultTemplate: 'modern',
        websitePatternClass: 'border-rose-200/70 bg-rose-50/80',
        websiteFeatureClass: 'bg-rose-50 text-rose-950',
        websiteAccentClass: 'text-rose-700',
        websiteProofLabel: 'Early learning care'
    },
    mosque: {
        eyebrow: 'মসজিদ',
        heroLine: 'ইবাদত, ঘোষণা ও স্বচ্ছ হিসাবের ডিজিটাল কেন্দ্র',
        accent: 'emerald',
        surface: 'from-emerald-50 via-white to-teal-50',
        badge: 'bg-emerald-100 text-emerald-700',
        button: 'bg-emerald-600 hover:bg-emerald-700',
        iconWrap: 'bg-emerald-100 text-emerald-700',
        primaryColor: '#047857',
        fontFamily: 'hind_siliguri',
        defaultTemplate: 'dark_madrasa',
        websitePatternClass: 'border-emerald-300/20 bg-emerald-200/[0.06]',
        websiteFeatureClass: 'bg-emerald-300/[0.08] text-white',
        websiteAccentClass: 'text-emerald-200',
        websiteProofLabel: 'Community trust'
    }
};

export function getInstitutionDesignProfile(category) {
    return INSTITUTION_DESIGN_PROFILES[category] || INSTITUTION_DESIGN_PROFILES.high_school;
}

export const INSTITUTION_FONT_OPTIONS = [
    { value: 'hind_siliguri', label: 'Hind Siliguri' },
    { value: 'noto_sans_bengali', label: 'Noto Sans Bengali' },
    { value: 'system', label: 'System' }
];

export const SCHOOL_WEBSITE_TEMPLATES = [
    {
        value: 'classic',
        label: 'Classic Academy',
        description: 'গম্ভীর, পরিচ্ছন্ন, ঐতিহ্যধর্মী school look',
        shellClass: 'bg-[#fffdf9]',
        sectionClass: 'bg-[#f5f3ee]',
        cardClass: 'rounded-2xl',
        headerClass: 'bg-[var(--school-primary)] text-white',
        noticeClass: 'border-amber-200 bg-amber-50 text-amber-900',
        heroClass: 'bg-[var(--school-primary)] text-white',
        heroGridClass: 'lg:grid-cols-[1fr_0.85fr]',
        heroTitleClass: 'md:text-5xl',
        statClass: 'border-white/15 bg-white/10 text-white',
        statValueClass: 'text-amber-300',
        previewClass: 'lg:grid-cols-[0.8fr_1fr]',
        sectionTitleClass: 'text-slate-900'
    },
    {
        value: 'modern',
        label: 'Modern Campus',
        description: 'হালকা, উজ্জ্বল, সমসাময়িক layout',
        shellClass: 'bg-slate-50',
        sectionClass: 'bg-white',
        cardClass: 'rounded-[28px]',
        headerClass: 'bg-white text-slate-950',
        noticeClass: 'border-cyan-100 bg-cyan-50 text-cyan-950',
        heroClass: 'relative overflow-hidden bg-[var(--school-primary)] text-white',
        heroGridClass: 'lg:grid-cols-[0.9fr_1.1fr]',
        heroTitleClass: 'md:text-6xl',
        statClass: 'border-white/10 bg-white text-slate-950 shadow-2xl shadow-slate-950/15',
        statValueClass: 'text-[var(--school-primary)]',
        previewClass: 'lg:grid-cols-[1fr_1fr]',
        sectionTitleClass: 'text-slate-950'
    },
    {
        value: 'editorial',
        label: 'Editorial School',
        description: 'বড় typography, শান্ত layout, premium feel',
        shellClass: 'bg-[#fcfbf7]',
        sectionClass: 'bg-[#f2efe7]',
        cardClass: 'rounded-none',
        headerClass: 'border-b border-slate-900 bg-[#fcfbf7] text-slate-950',
        noticeClass: 'border-slate-300 bg-transparent text-slate-800',
        heroClass: 'border-b border-slate-900 bg-[#fcfbf7] text-slate-950',
        heroGridClass: 'lg:grid-cols-[1.15fr_0.65fr]',
        heroTitleClass: 'md:text-6xl',
        statClass: 'border-t border-slate-900 bg-transparent text-slate-950',
        statValueClass: 'text-slate-950',
        previewClass: 'lg:grid-cols-[1fr_0.8fr]',
        sectionTitleClass: 'text-slate-950'
    },
    {
        value: 'dark_school',
        label: 'Neon School Dark',
        description: 'violet, magenta ও neon accent সহ modern school website',
        tone: 'dark',
        shellClass: 'bg-[#0A0118] text-white',
        sectionClass: 'bg-[#15082C]',
        cardClass: 'rounded-[24px]',
        headerClass: 'border-b border-white/10 bg-[#0A0118]/90 text-white backdrop-blur-xl',
        noticeClass: 'border-violet-500/30 bg-[#15082C] text-white',
        heroClass: 'relative overflow-hidden bg-[#0A0118] text-white',
        heroGridClass: 'lg:grid-cols-[1fr_0.95fr]',
        heroTitleClass: 'md:text-6xl',
        statClass: 'border-white/10 bg-white/[0.04] text-white shadow-2xl shadow-violet-950/20',
        statValueClass: 'bg-gradient-to-r from-[#FFB800] via-[#FF6B35] to-[#EC4899] bg-clip-text text-transparent',
        previewClass: 'lg:grid-cols-[0.85fr_1fr]',
        sectionTitleClass: 'text-white',
        accentTextClass: 'text-[#00F5D4]',
        mutedTextClass: 'text-white/60',
        bodyTextClass: 'text-white/72',
        cardSurfaceClass: 'border border-white/10 bg-white/[0.04] text-white shadow-xl shadow-violet-950/20 backdrop-blur-xl',
        cardSoftClass: 'border border-violet-400/25 bg-[#1E0D3F]/70 text-white backdrop-blur-xl',
        primaryButtonClass: 'bg-gradient-to-r from-[#EC4899] to-[#7C3AED] text-white shadow-lg shadow-pink-500/30',
        ghostButtonClass: 'border border-white/20 bg-white/[0.05] text-white hover:border-[#00F5D4]/60',
        logoClass: 'bg-gradient-to-br from-[#EC4899] to-[#7C3AED] text-white shadow-lg shadow-pink-500/30',
        noticeBadgeClass: 'bg-gradient-to-r from-[#EC4899] to-[#7C3AED] text-white',
        heroAccentClass: 'bg-gradient-to-r from-[#EC4899] via-[#7C3AED] to-[#00F5D4] bg-clip-text text-transparent',
        sectionHeadingClass: 'text-white',
        gridOverlay: 'violet'
    },
    {
        value: 'dark_college',
        label: 'College Blue Dark',
        description: 'blue/cyan/orange glow সহ college website',
        tone: 'dark',
        shellClass: 'bg-[#020918] text-white',
        sectionClass: 'bg-[#070F2B]',
        cardClass: 'rounded-[22px]',
        headerClass: 'border-b border-blue-500/20 bg-[#020918]/90 text-white backdrop-blur-xl',
        noticeClass: 'border-blue-500/30 bg-[#070F2B] text-white',
        heroClass: 'relative overflow-hidden bg-[#020918] text-white',
        heroGridClass: 'lg:grid-cols-[1fr_0.95fr]',
        heroTitleClass: 'md:text-6xl',
        statClass: 'border-white/10 bg-white/[0.035] text-white shadow-2xl shadow-blue-950/20',
        statValueClass: 'bg-gradient-to-r from-[#F97316] to-[#FBBF24] bg-clip-text text-transparent',
        previewClass: 'lg:grid-cols-[0.9fr_1fr]',
        sectionTitleClass: 'text-white',
        accentTextClass: 'text-[#00D4FF]',
        mutedTextClass: 'text-white/58',
        bodyTextClass: 'text-white/72',
        cardSurfaceClass: 'border border-white/10 bg-white/[0.035] text-white shadow-xl shadow-blue-950/20 backdrop-blur-xl',
        cardSoftClass: 'border border-blue-400/25 bg-[#0D1A42]/75 text-white backdrop-blur-xl',
        primaryButtonClass: 'bg-gradient-to-r from-[#2563EB] to-[#06B6D4] text-white shadow-lg shadow-blue-500/30',
        ghostButtonClass: 'border border-white/20 bg-white/[0.04] text-white hover:border-[#00D4FF]/60',
        logoClass: 'bg-gradient-to-br from-[#2563EB] to-[#06B6D4] text-white shadow-lg shadow-blue-500/30',
        noticeBadgeClass: 'bg-gradient-to-r from-[#2563EB] to-[#06B6D4] text-white',
        heroAccentClass: 'bg-gradient-to-r from-[#06B6D4] via-[#2563EB] to-[#00D4FF] bg-clip-text text-transparent',
        sectionHeadingClass: 'text-white',
        gridOverlay: 'blue'
    },
    {
        value: 'dark_madrasa',
        label: 'Madrasa Emerald Dark',
        description: 'emerald/gold Islamic inspired madrasa website',
        tone: 'dark',
        shellClass: 'bg-[#020E08] text-white',
        sectionClass: 'bg-[#071A10]',
        cardClass: 'rounded-[22px]',
        headerClass: 'border-b border-emerald-500/20 bg-[#020E08]/90 text-white backdrop-blur-xl',
        noticeClass: 'border-emerald-500/30 bg-[#071A10] text-white',
        heroClass: 'relative overflow-hidden bg-[#020E08] text-white',
        heroGridClass: 'lg:grid-cols-[1fr_0.95fr]',
        heroTitleClass: 'md:text-6xl',
        statClass: 'border-white/10 bg-white/[0.035] text-white shadow-2xl shadow-emerald-950/20',
        statValueClass: 'bg-gradient-to-r from-[#D4AF37] via-[#059669] to-[#00FFB3] bg-clip-text text-transparent',
        previewClass: 'lg:grid-cols-[0.9fr_1fr]',
        sectionTitleClass: 'text-white',
        accentTextClass: 'text-[#00FFB3]',
        mutedTextClass: 'text-white/58',
        bodyTextClass: 'text-white/72',
        cardSurfaceClass: 'border border-white/10 bg-white/[0.035] text-white shadow-xl shadow-emerald-950/20 backdrop-blur-xl',
        cardSoftClass: 'border border-emerald-400/25 bg-[#0D2818]/75 text-white backdrop-blur-xl',
        primaryButtonClass: 'bg-gradient-to-r from-[#059669] to-[#00FFB3] text-white shadow-lg shadow-emerald-500/30',
        ghostButtonClass: 'border border-white/20 bg-white/[0.04] text-white hover:border-[#00FFB3]/60',
        logoClass: 'bg-gradient-to-br from-[#059669] to-[#D4AF37] text-white shadow-lg shadow-emerald-500/30',
        noticeBadgeClass: 'bg-gradient-to-r from-[#059669] to-[#D4AF37] text-white',
        heroAccentClass: 'bg-gradient-to-r from-[#D4AF37] via-[#059669] to-[#00FFB3] bg-clip-text text-transparent',
        sectionHeadingClass: 'text-white',
        gridOverlay: 'emerald'
    }
];

export function getSchoolWebsiteTemplate(template) {
    return SCHOOL_WEBSITE_TEMPLATES.find((item) => item.value === template) || SCHOOL_WEBSITE_TEMPLATES[0];
}

export const INSTITUTION_MENU_OPTIONS = [
    { value: 'home', label: 'হোম' },
    { value: 'about', label: 'আমাদের সম্পর্কে' },
    { value: 'teachers', label: 'শিক্ষক' },
    { value: 'academics', label: 'শিক্ষা কার্যক্রম' },
    { value: 'results', label: 'ফলাফল' },
    { value: 'notices', label: 'নোটিশ' },
    { value: 'contact', label: 'যোগাযোগ' }
];
