export const INSTITUTION_DESIGN_PROFILES = {
    primary_school: {
        eyebrow: 'প্রাইমারি স্কুল',
        heroLine: 'শিশুর শেখা, উপস্থিতি ও অগ্রগতি একসাথে',
        accent: 'teal',
        surface: 'from-teal-50 via-white to-cyan-50',
        badge: 'bg-teal-100 text-teal-800',
        button: 'bg-teal-700 hover:bg-teal-800',
        iconWrap: 'bg-teal-100 text-teal-800',
        primaryColor: '#0f766e',
        accentColor: '#f4b942',
        fontFamily: 'hind_siliguri',
        defaultTemplate: 'dark_school',
        websitePatternClass: 'border-teal-200/70 bg-teal-50/80',
        websiteFeatureClass: 'bg-teal-50 text-teal-950',
        websiteAccentClass: 'text-teal-800',
        websiteProofLabel: 'Foundational care'
    },
    high_school: {
        eyebrow: 'হাই স্কুল',
        heroLine: 'শৃঙ্খলা, ফলাফল ও ভবিষ্যৎ প্রস্তুতির ডিজিটাল কেন্দ্র',
        accent: 'teal',
        surface: 'from-teal-50 via-white to-cyan-50',
        badge: 'bg-teal-100 text-teal-700',
        button: 'bg-teal-600 hover:bg-teal-700',
        iconWrap: 'bg-teal-100 text-teal-700',
        primaryColor: '#0f766e',
        accentColor: '#f4b942',
        fontFamily: 'hind_siliguri',
        defaultTemplate: 'dark_school',
        websitePatternClass: 'border-teal-100 bg-teal-50/70',
        websiteFeatureClass: 'bg-teal-50 text-teal-950',
        websiteAccentClass: 'text-teal-700',
        websiteProofLabel: 'School command center'
    },
    college: {
        eyebrow: 'কলেজ',
        heroLine: 'বিষয়ভিত্তিক শিক্ষা, ফলাফল ও উচ্চশিক্ষা ট্র্যাকিং',
        accent: 'navy',
        surface: 'from-slate-100 via-white to-amber-50',
        badge: 'bg-[#e8eef5] text-[#0b1f3a]',
        button: 'bg-[#0b1f3a] hover:bg-[#132f52]',
        iconWrap: 'bg-[#e8eef5] text-[#0b1f3a]',
        primaryColor: '#0b1f3a',
        accentColor: '#c99a2e',
        fontFamily: 'hind_siliguri',
        defaultTemplate: 'dark_college',
        websitePatternClass: 'border-slate-200 bg-[#f4f7fa]',
        websiteFeatureClass: 'bg-[#eef2f6] text-[#0b1f3a]',
        websiteAccentClass: 'text-[#9a7118]',
        websiteProofLabel: 'Higher study track'
    },
    alim_madrasa: {
        eyebrow: 'আলিম মাদ্রাসা',
        heroLine: 'দ্বীনি শিক্ষা ও আধুনিক ব্যবস্থাপনার সমন্বয়',
        accent: 'emerald',
        surface: 'from-emerald-50 via-white to-lime-50',
        badge: 'bg-emerald-100 text-emerald-700',
        button: 'bg-emerald-600 hover:bg-emerald-700',
        iconWrap: 'bg-emerald-100 text-emerald-700',
        primaryColor: '#0b6b4f',
        accentColor: '#c7a448',
        fontFamily: 'hind_siliguri',
        defaultTemplate: 'dark_madrasa',
        websitePatternClass: 'border-emerald-200/80 bg-[#f4f7ef]',
        websiteFeatureClass: 'bg-[#eef6ed] text-emerald-950',
        websiteAccentClass: 'text-emerald-700',
        websiteProofLabel: 'Deen and academics'
    },
    dakhil_madrasa: {
        eyebrow: 'দাখিল মাদ্রাসা',
        heroLine: 'ইবতেদায়ি থেকে দাখিল পর্যন্ত দ্বীনি ও সাধারণ শিক্ষার সমন্বিত পথচলা',
        accent: 'emerald',
        surface: 'from-emerald-50 via-white to-lime-50',
        badge: 'bg-emerald-100 text-emerald-700',
        button: 'bg-emerald-600 hover:bg-emerald-700',
        iconWrap: 'bg-emerald-100 text-emerald-700',
        primaryColor: '#0b6b4f',
        accentColor: '#c7a448',
        fontFamily: 'hind_siliguri',
        defaultTemplate: 'dark_madrasa',
        websitePatternClass: 'border-emerald-200/80 bg-[#f4f7ef]',
        websiteFeatureClass: 'bg-[#eef6ed] text-emerald-950',
        websiteAccentClass: 'text-emerald-700',
        websiteProofLabel: 'Deen and academics'
    },
    kindergarten: {
        eyebrow: 'কিন্ডারগার্টেন',
        heroLine: 'আনন্দময় শেখা, নিরাপদ যত্ন ও অভিভাবক সংযোগ',
        accent: 'coral',
        surface: 'from-orange-50 via-white to-yellow-50',
        badge: 'bg-orange-100 text-orange-800',
        button: 'bg-[#ef624d] hover:bg-[#dc4f3b]',
        iconWrap: 'bg-[#ffe4dc] text-[#c94735]',
        primaryColor: '#ef624d',
        accentColor: '#f7c948',
        fontFamily: 'hind_siliguri',
        defaultTemplate: 'kindergarten_playful',
        websitePatternClass: 'border-orange-200/80 bg-[#fff3ed]',
        websiteFeatureClass: 'bg-[#fff0e7] text-[#6f2d24]',
        websiteAccentClass: 'text-[#c94735]',
        websiteProofLabel: 'Early learning care'
    },
    mosque: {
        eyebrow: 'মসজিদ',
        heroLine: 'ইবাদত, ঘোষণা ও স্বচ্ছ হিসাবের ডিজিটাল কেন্দ্র',
        accent: 'emerald',
        surface: 'from-emerald-50 via-white to-teal-50',
        badge: 'bg-emerald-100 text-emerald-700',
        button: 'bg-emerald-600 hover:bg-emerald-700',
        iconWrap: 'bg-emerald-100 text-emerald-700',
        primaryColor: '#047857',
        fontFamily: 'hind_siliguri',
        defaultTemplate: 'dark_madrasa',
        websitePatternClass: 'border-emerald-300/20 bg-emerald-200/[0.06]',
        websiteFeatureClass: 'bg-emerald-300/[0.08] text-white',
        websiteAccentClass: 'text-emerald-200',
        websiteProofLabel: 'Community trust'
    }
};

export function getInstitutionDesignProfile(category) {
    return INSTITUTION_DESIGN_PROFILES[category] || INSTITUTION_DESIGN_PROFILES.high_school;
}

export const INSTITUTION_FONT_OPTIONS = [
    { value: 'hind_siliguri', label: 'Hind Siliguri' },
    { value: 'noto_sans_bengali', label: 'Noto Sans Bengali' },
    { value: 'system', label: 'System' }
];

export const SCHOOL_WEBSITE_TEMPLATES = [
    {
        value: 'classic',
        label: 'Classic Academy',
        description: 'গম্ভীর, পরিচ্ছন্ন, ঐতিহ্যধর্মী school look',
        shellClass: 'bg-[#fffdf9]',
        sectionClass: 'bg-[#f5f3ee]',
        cardClass: 'rounded-2xl',
        headerClass: 'bg-[var(--school-primary)] text-white',
        noticeClass: 'border-amber-200 bg-amber-50 text-amber-900',
        heroClass: 'bg-[var(--school-primary)] text-white',
        heroGridClass: 'lg:grid-cols-[1fr_0.85fr]',
        heroTitleClass: 'md:text-5xl',
        statClass: 'border-white/15 bg-white/10 text-white',
        statValueClass: 'text-amber-300',
        previewClass: 'lg:grid-cols-[0.8fr_1fr]',
        sectionTitleClass: 'text-slate-900'
    },
    {
        value: 'modern',
        label: 'Modern Campus',
        description: 'হালকা, উজ্জ্বল, সমসাময়িক layout',
        shellClass: 'bg-slate-50',
        sectionClass: 'bg-white',
        cardClass: 'rounded-[28px]',
        headerClass: 'bg-white text-slate-950',
        noticeClass: 'border-cyan-100 bg-cyan-50 text-cyan-950',
        heroClass: 'relative overflow-hidden bg-[var(--school-primary)] text-white',
        heroGridClass: 'lg:grid-cols-[0.9fr_1.1fr]',
        heroTitleClass: 'md:text-6xl',
        statClass: 'border-white/10 bg-white text-slate-950 shadow-2xl shadow-slate-950/15',
        statValueClass: 'text-[var(--school-primary)]',
        previewClass: 'lg:grid-cols-[1fr_1fr]',
        sectionTitleClass: 'text-slate-950'
    },
    {
        value: 'kindergarten_playful',
        label: 'Playful Kindergarten',
        description: 'Warm coral, sunshine yellow and child-friendly rounded layout',
        shellClass: 'bg-[#fff9f4] text-[#412b28]',
        sectionClass: 'bg-[#fff0e7]',
        cardClass: 'rounded-[30px]',
        headerClass: 'border-b border-orange-100 bg-white/95 text-[#412b28] backdrop-blur-xl',
        noticeClass: 'border-orange-200 bg-[#fff3dc] text-[#6b3b1f]',
        heroClass: 'relative overflow-hidden bg-[#ef624d] text-white',
        heroGridClass: 'lg:grid-cols-[0.9fr_1.1fr]',
        heroTitleClass: 'md:text-6xl',
        statClass: 'border border-orange-100 bg-white text-[#412b28] shadow-lg shadow-orange-950/5',
        statValueClass: 'text-[#ef624d]',
        previewClass: 'lg:grid-cols-[0.9fr_1fr]',
        sectionTitleClass: 'text-[#412b28]',
        accentTextClass: 'text-[#c94735]',
        mutedTextClass: 'text-[#8a625c]',
        bodyTextClass: 'text-white/88',
        cardSurfaceClass: 'border border-orange-100 bg-white text-[#412b28] shadow-lg shadow-orange-950/5',
        cardSoftClass: 'border border-orange-100 bg-[#fff0e7] text-[#5e332c]',
        primaryButtonClass: 'bg-[#f7c948] text-[#412b28] shadow-lg shadow-amber-500/20 hover:bg-[#ffda68]',
        ghostButtonClass: 'border border-white/50 bg-white/10 text-white hover:bg-white/20',
        logoClass: 'bg-[#ef624d] text-white shadow-lg shadow-orange-500/20',
        noticeBadgeClass: 'bg-[#ef624d] text-white',
        heroAccentClass: 'text-[#fff0a8]',
        sectionHeadingClass: 'text-[#412b28]',
        gridOverlay: 'coral'
    },
    {
        value: 'editorial',
        label: 'Editorial School',
        description: 'বড় typography, শান্ত layout, premium feel',
        shellClass: 'bg-[#fcfbf7]',
        sectionClass: 'bg-[#f2efe7]',
        cardClass: 'rounded-none',
        headerClass: 'border-b border-slate-900 bg-[#fcfbf7] text-slate-950',
        noticeClass: 'border-slate-300 bg-transparent text-slate-800',
        heroClass: 'border-b border-slate-900 bg-[#fcfbf7] text-slate-950',
        heroGridClass: 'lg:grid-cols-[1.15fr_0.65fr]',
        heroTitleClass: 'md:text-6xl',
        statClass: 'border-t border-slate-900 bg-transparent text-slate-950',
        statValueClass: 'text-slate-950',
        previewClass: 'lg:grid-cols-[1fr_0.8fr]',
        sectionTitleClass: 'text-slate-950'
    },
    {
        value: 'dark_school',
        label: 'School Showcase',
        description: 'premium hero slider, notice board and guardian-focused school homepage',
        tone: 'dark',
        shellClass: 'bg-[#0A0118] text-white',
        sectionClass: 'bg-[#15082C]',
        cardClass: 'rounded-[24px]',
        headerClass: 'border-b border-white/10 bg-[#0A0118]/90 text-white backdrop-blur-xl',
        noticeClass: 'border-violet-500/30 bg-[#15082C] text-white',
        heroClass: 'relative overflow-hidden bg-[#0A0118] text-white',
        heroGridClass: 'lg:grid-cols-[1fr_0.95fr]',
        heroTitleClass: 'md:text-6xl',
        statClass: 'border-white/10 bg-white/[0.04] text-white shadow-2xl shadow-violet-950/20',
        statValueClass: 'bg-gradient-to-r from-[#FFB800] via-[#FF6B35] to-[#EC4899] bg-clip-text text-transparent',
        previewClass: 'lg:grid-cols-[0.85fr_1fr]',
        sectionTitleClass: 'text-white',
        accentTextClass: 'text-[#00F5D4]',
        mutedTextClass: 'text-white/60',
        bodyTextClass: 'text-white/72',
        cardSurfaceClass: 'border border-white/10 bg-white/[0.04] text-white shadow-xl shadow-violet-950/20 backdrop-blur-xl',
        cardSoftClass: 'border border-violet-400/25 bg-[#1E0D3F]/70 text-white backdrop-blur-xl',
        primaryButtonClass: 'bg-gradient-to-r from-[#EC4899] to-[#7C3AED] text-white shadow-lg shadow-pink-500/30',
        ghostButtonClass: 'border border-white/20 bg-white/[0.05] text-white hover:border-[#00F5D4]/60',
        logoClass: 'bg-gradient-to-br from-[#EC4899] to-[#7C3AED] text-white shadow-lg shadow-pink-500/30',
        noticeBadgeClass: 'bg-gradient-to-r from-[#EC4899] to-[#7C3AED] text-white',
        heroAccentClass: 'bg-gradient-to-r from-[#EC4899] via-[#7C3AED] to-[#00F5D4] bg-clip-text text-transparent',
        sectionHeadingClass: 'text-white',
        gridOverlay: 'violet'
    },
    {
        value: 'dark_college',
        label: 'College Showcase',
        description: 'department, admission, results and career sections for colleges',
        tone: 'dark',
        shellClass: 'bg-[#020918] text-white',
        sectionClass: 'bg-[#070F2B]',
        cardClass: 'rounded-[22px]',
        headerClass: 'border-b border-blue-500/20 bg-[#020918]/90 text-white backdrop-blur-xl',
        noticeClass: 'border-blue-500/30 bg-[#070F2B] text-white',
        heroClass: 'relative overflow-hidden bg-[#020918] text-white',
        heroGridClass: 'lg:grid-cols-[1fr_0.95fr]',
        heroTitleClass: 'md:text-6xl',
        statClass: 'border-white/10 bg-white/[0.035] text-white shadow-2xl shadow-blue-950/20',
        statValueClass: 'bg-gradient-to-r from-[#F97316] to-[#FBBF24] bg-clip-text text-transparent',
        previewClass: 'lg:grid-cols-[0.9fr_1fr]',
        sectionTitleClass: 'text-white',
        accentTextClass: 'text-[#00D4FF]',
        mutedTextClass: 'text-white/58',
        bodyTextClass: 'text-white/72',
        cardSurfaceClass: 'border border-white/10 bg-white/[0.035] text-white shadow-xl shadow-blue-950/20 backdrop-blur-xl',
        cardSoftClass: 'border border-blue-400/25 bg-[#0D1A42]/75 text-white backdrop-blur-xl',
        primaryButtonClass: 'bg-gradient-to-r from-[#2563EB] to-[#06B6D4] text-white shadow-lg shadow-blue-500/30',
        ghostButtonClass: 'border border-white/20 bg-white/[0.04] text-white hover:border-[#00D4FF]/60',
        logoClass: 'bg-gradient-to-br from-[#2563EB] to-[#06B6D4] text-white shadow-lg shadow-blue-500/30',
        noticeBadgeClass: 'bg-gradient-to-r from-[#2563EB] to-[#06B6D4] text-white',
        heroAccentClass: 'bg-gradient-to-r from-[#06B6D4] via-[#2563EB] to-[#00D4FF] bg-clip-text text-transparent',
        sectionHeadingClass: 'text-white',
        gridOverlay: 'blue'
    },
    {
        value: 'dark_madrasa',
        label: 'Madrasha Showcase',
        description: 'emerald and gold layout for Dakhil, Alim and Islamic institutions',
        tone: 'dark',
        shellClass: 'bg-[#020E08] text-white',
        sectionClass: 'bg-[#071A10]',
        cardClass: 'rounded-[22px]',
        headerClass: 'border-b border-emerald-500/20 bg-[#020E08]/90 text-white backdrop-blur-xl',
        noticeClass: 'border-emerald-500/30 bg-[#071A10] text-white',
        heroClass: 'relative overflow-hidden bg-[#020E08] text-white',
        heroGridClass: 'lg:grid-cols-[1fr_0.95fr]',
        heroTitleClass: 'md:text-6xl',
        statClass: 'border-white/10 bg-white/[0.035] text-white shadow-2xl shadow-emerald-950/20',
        statValueClass: 'bg-gradient-to-r from-[#D4AF37] via-[#059669] to-[#00FFB3] bg-clip-text text-transparent',
        previewClass: 'lg:grid-cols-[0.9fr_1fr]',
        sectionTitleClass: 'text-white',
        accentTextClass: 'text-[#00FFB3]',
        mutedTextClass: 'text-white/58',
        bodyTextClass: 'text-white/72',
        cardSurfaceClass: 'border border-white/10 bg-white/[0.035] text-white shadow-xl shadow-emerald-950/20 backdrop-blur-xl',
        cardSoftClass: 'border border-emerald-400/25 bg-[#0D2818]/75 text-white backdrop-blur-xl',
        primaryButtonClass: 'bg-gradient-to-r from-[#059669] to-[#00FFB3] text-white shadow-lg shadow-emerald-500/30',
        ghostButtonClass: 'border border-white/20 bg-white/[0.04] text-white hover:border-[#00FFB3]/60',
        logoClass: 'bg-gradient-to-br from-[#059669] to-[#D4AF37] text-white shadow-lg shadow-emerald-500/30',
        noticeBadgeClass: 'bg-gradient-to-r from-[#059669] to-[#D4AF37] text-white',
        heroAccentClass: 'bg-gradient-to-r from-[#D4AF37] via-[#059669] to-[#00FFB3] bg-clip-text text-transparent',
        sectionHeadingClass: 'text-white',
        gridOverlay: 'emerald'
    }
];

const LIGHT_TEMPLATE_OVERRIDES = {
    dark_school: {
        label: 'Teal School Campus',
        description: 'Confident teal school identity with warm gold actions',
        shellClass: 'bg-[#f5f8f7] text-slate-950',
        sectionClass: 'bg-white',
        cardClass: 'rounded-[18px]',
        headerClass: 'border-b border-teal-100 bg-white/95 text-slate-950 backdrop-blur-xl',
        noticeClass: 'border-teal-200 bg-teal-50 text-teal-950',
        heroClass: 'relative overflow-hidden bg-[#073f3c] text-white',
        heroGridClass: 'lg:grid-cols-[1fr_0.82fr]',
        heroTitleClass: 'md:text-6xl',
        statClass: 'border border-slate-200 bg-white text-slate-950 shadow-sm',
        statValueClass: 'text-[var(--school-primary)]',
        previewClass: 'lg:grid-cols-[0.86fr_1fr]',
        sectionTitleClass: 'text-slate-950',
        mutedTextClass: 'text-slate-500',
        bodyTextClass: 'text-white/82',
        cardSurfaceClass: 'border border-teal-100 bg-white text-slate-950 shadow-sm',
        cardSoftClass: 'border border-teal-100 bg-teal-50/70 text-slate-950',
        primaryButtonClass: 'bg-[#f4b942] text-[#143b38] shadow-lg shadow-amber-500/20 hover:bg-[#ffd36b]',
        ghostButtonClass: 'border border-white/40 bg-white/10 text-white hover:bg-white/20',
        logoClass: 'bg-[#0f766e] text-white',
        noticeBadgeClass: 'bg-[#0f766e] text-white',
        heroAccentClass: 'text-[#f8d477]',
        sectionHeadingClass: 'text-slate-950',
        tone: undefined
    },
    dark_college: {
        label: 'Navy & Gold College',
        description: 'Professional navy campus identity with restrained gold accents',
        shellClass: 'bg-[#f7f8fa] text-slate-950',
        sectionClass: 'bg-white',
        cardClass: 'rounded-[18px]',
        headerClass: 'border-b border-[#dce3eb] bg-white/95 text-[#0b1f3a] backdrop-blur-xl',
        noticeClass: 'border-[#e4d3a6] bg-[#fff9e9] text-[#4f3b13]',
        heroClass: 'relative overflow-hidden bg-[#071a33] text-white',
        heroGridClass: 'lg:grid-cols-[1.08fr_0.82fr]',
        heroTitleClass: 'md:text-6xl',
        statClass: 'border border-slate-200 bg-white text-slate-950 shadow-sm',
        statValueClass: 'text-[var(--school-primary)]',
        previewClass: 'lg:grid-cols-[0.9fr_1fr]',
        sectionTitleClass: 'text-slate-950',
        mutedTextClass: 'text-slate-500',
        bodyTextClass: 'text-white/82',
        cardSurfaceClass: 'border border-[#dce3eb] bg-white text-[#0b1f3a] shadow-sm',
        cardSoftClass: 'border border-[#d9e1ea] bg-[#eef2f6] text-[#0b1f3a]',
        primaryButtonClass: 'bg-[#c99a2e] text-[#0b1f3a] shadow-lg shadow-amber-600/20 hover:bg-[#dfb754]',
        ghostButtonClass: 'border border-white/40 bg-white/10 text-white hover:bg-white/20',
        logoClass: 'bg-[#0b1f3a] text-white',
        noticeBadgeClass: 'bg-[#0b1f3a] text-white',
        heroAccentClass: 'text-[#e2bd63]',
        sectionHeadingClass: 'text-slate-950',
        tone: undefined
    },
    dark_madrasa: {
        label: 'Emerald & Ivory Madrasa',
        description: 'Calm emerald, ivory and muted gold Islamic academic identity',
        shellClass: 'bg-[#fbf8ef] text-[#17372d]',
        sectionClass: 'bg-[#fffdf7]',
        cardClass: 'rounded-[18px]',
        headerClass: 'border-b border-emerald-100 bg-[#fffdf7]/95 text-[#17372d] backdrop-blur-xl',
        noticeClass: 'border-emerald-200 bg-[#eef6ed] text-emerald-950',
        heroClass: 'relative overflow-hidden bg-[#064b3b] text-white',
        heroGridClass: 'lg:grid-cols-[1fr_0.82fr]',
        heroTitleClass: 'md:text-6xl',
        statClass: 'border border-emerald-100 bg-white text-slate-950 shadow-sm',
        statValueClass: 'text-[var(--school-primary)]',
        previewClass: 'lg:grid-cols-[0.9fr_1fr]',
        sectionTitleClass: 'text-slate-950',
        mutedTextClass: 'text-slate-500',
        bodyTextClass: 'text-white/82',
        cardSurfaceClass: 'border border-emerald-100 bg-[#fffdf7] text-[#17372d] shadow-sm',
        cardSoftClass: 'border border-emerald-100 bg-[#eef6ed] text-[#17372d]',
        primaryButtonClass: 'bg-[#c7a448] text-[#17372d] shadow-lg shadow-amber-600/15 hover:bg-[#d9bd72]',
        ghostButtonClass: 'border border-white/40 bg-white/10 text-white hover:bg-white/20',
        logoClass: 'bg-[#0b6b4f] text-white',
        noticeBadgeClass: 'bg-[#0b6b4f] text-white',
        heroAccentClass: 'text-[#dfca8b]',
        sectionHeadingClass: 'text-slate-950',
        tone: undefined
    }
};

export function getSchoolWebsiteTemplate(template) {
    const base = SCHOOL_WEBSITE_TEMPLATES.find((item) => item.value === template) || SCHOOL_WEBSITE_TEMPLATES[0];
    return LIGHT_TEMPLATE_OVERRIDES[base.value]
        ? { ...base, ...LIGHT_TEMPLATE_OVERRIDES[base.value] }
        : base;
}

export const INSTITUTION_MENU_OPTIONS = [
    { value: 'home', label: 'হোম' },
    { value: 'about', label: 'আমাদের সম্পর্কে' },
    { value: 'teachers', label: 'শিক্ষক' },
    { value: 'academics', label: 'শিক্ষা কার্যক্রম' },
    { value: 'results', label: 'ফলাফল' },
    { value: 'notices', label: 'নোটিশ' },
    { value: 'contact', label: 'যোগাযোগ' }
];
