export const paths = {
    home: '/',
    homeHousehold: '/#citizen-services',
    login: '/login',
    citizen: '/citizen',
    citizenServices: '/citizen/services',
    area: '/area',
    lostFound: '/lost-found',
    voiceGuide: '/voice-guide',
    admin: '/admin',
    campus: '/campus',
    campusProgress: '/campus/progress',
    futureAi: '/future-ai',
    roadmap: '/roadmap',
    business: '/business',
    service: (slug) => `/services/${slug}`,
    unionPortal: (unionSlug) => `/u/${unionSlug}`,
    wardPortal: (_unionSlug, wardIdOrSlug) => `/w/${wardIdOrSlug}`,
    villagePortal: (_unionSlug, _wardIdOrSlug, villageIdOrSlug) => `/g/${villageIdOrSlug}`,
};
