import {
    Droplet,
    FileText,
    School,
    Phone,
    PackageSearch,
    Newspaper,
    Gift,
    Heart,
    Store,
    GraduationCap,
    LayoutGrid,
    Library,
    Zap,
    Wrench,
    Tractor,
    ShieldAlert,
} from 'lucide-react';
import { paths } from '@/lib/constants/paths';

/**
 * একই তালিকা — হিরো, সার্ভিস গ্রিড, হেডার কুইক-লিঙ্ক। `href` = স্ট্যাটিক রাউট।
 */
export const SERVICE_CATEGORIES = [
    {
        id: 'blood',
        level: 'global',
        title: 'ব্লাড ব্যাংক',
        subtitle: 'গ্রাম ভিত্তিক দ্রুত রক্তদাতা',
        icon: Droplet,
        gradient: 'from-rose-500 via-orange-500 to-amber-500',
        softBg: 'bg-rose-500/12',
        ring: 'ring-rose-500/25',
        iconTint: 'text-rose-600',
        featured: true,
        free: true,
        href: paths.service('blood'),
    },
    {
        id: 'e-up',
        level: 'union',
        title: 'ই-ইউপি সেবা',
        subtitle: 'আবেদন, ফি ও ট্র্যাকিং',
        icon: FileText,
        gradient: 'from-sky-500 via-blue-600 to-indigo-600',
        softBg: 'bg-sky-500/12',
        ring: 'ring-sky-500/25',
        iconTint: 'text-sky-600',
        featured: true,
        free: false,
        href: paths.service('e-up'),
    },
    {
        id: 'school',
        level: 'global',
        title: 'স্মার্ট স্কুল',
        subtitle: 'হাজিরা এসএমএস ও ফলাফল',
        icon: School,
        gradient: 'from-violet-500 via-purple-600 to-fuchsia-600',
        softBg: 'bg-violet-500/12',
        ring: 'ring-violet-500/25',
        iconTint: 'text-violet-600',
        featured: true,
        free: false,
        href: paths.service('school'),
    },
    {
        id: 'learning',
        level: 'global',
        title: 'লার্নিং হাব',
        subtitle: 'ইংরেজি ও গণিত—ট্রিক্স ও নোট',
        icon: Library,
        gradient: 'from-cyan-500 via-sky-600 to-blue-700',
        softBg: 'bg-cyan-500/12',
        ring: 'ring-cyan-500/25',
        iconTint: 'text-cyan-600',
        featured: false,
        free: true,
        href: paths.service('learning'),
    },
    {
        id: 'emergency',
        level: 'global',
        title: 'জরুরি নম্বর',
        subtitle: 'ডাক্তার, অ্যাম্বুলেন্স, ফায়ার',
        icon: Phone,
        gradient: 'from-orange-500 via-red-500 to-rose-600',
        softBg: 'bg-orange-500/12',
        ring: 'ring-orange-500/25',
        iconTint: 'text-orange-600',
        featured: false,
        free: true,
        href: paths.service('emergency'),
    },
    {
        id: 'lost',
        level: 'union',
        title: 'হারানো-প্রাপ্তি',
        subtitle: 'গরু, মোবাইল, দলিল',
        icon: PackageSearch,
        gradient: 'from-amber-500 via-yellow-500 to-lime-500',
        softBg: 'bg-amber-500/12',
        ring: 'ring-amber-500/25',
        iconTint: 'text-amber-700',
        featured: true,
        free: true,
        href: paths.service('lost'),
    },
    {
        id: 'news',
        level: 'union',
        title: 'লোকাল নিউজ',
        subtitle: 'জানাজা ও এলাকার খবর',
        icon: Newspaper,
        gradient: 'from-slate-600 via-slate-700 to-slate-900',
        softBg: 'bg-slate-500/10',
        ring: 'ring-slate-400/20',
        iconTint: 'text-slate-700',
        featured: false,
        free: true,
        href: paths.service('news'),
    },
    {
        id: 'donation',
        level: 'union',
        title: 'স্বচ্ছ দান',
        subtitle: 'ভেরিফাইড তালিকায় সাহায্য',
        icon: Gift,
        gradient: 'from-emerald-500 via-teal-500 to-cyan-600',
        softBg: 'bg-emerald-500/12',
        ring: 'ring-emerald-500/25',
        iconTint: 'text-emerald-600',
        featured: false,
        free: true,
        href: paths.service('donation'),
    },
    {
        id: 'islamic',
        level: 'global',
        title: 'ইসলামিক কর্নার',
        subtitle: 'নামাজ, হাদিস, নূরানী',
        icon: Heart,
        gradient: 'from-teal-500 via-emerald-600 to-green-600',
        softBg: 'bg-teal-500/12',
        ring: 'ring-teal-500/25',
        iconTint: 'text-teal-600',
        featured: true,
        free: true,
        href: paths.service('islamic'),
    },
    {
        id: 'market',
        level: 'union',
        title: 'গ্রাম বাজার',
        subtitle: 'সরাসরি কেনাবেচা',
        icon: Store,
        gradient: 'from-amber-400 via-orange-500 to-red-500',
        softBg: 'bg-amber-500/12',
        ring: 'ring-amber-500/20',
        iconTint: 'text-amber-600',
        featured: false,
        free: true,
        href: paths.service('market'),
    },
    {
        id: 'quiz',
        level: 'global',
        title: 'কুইজ হাব',
        subtitle: 'লিডারবোর্ড ও পুরস্কার',
        icon: GraduationCap,
        gradient: 'from-indigo-500 via-blue-600 to-violet-700',
        softBg: 'bg-indigo-500/12',
        ring: 'ring-indigo-500/25',
        iconTint: 'text-indigo-600',
        featured: false,
        free: true,
        href: paths.service('quiz'),
    },
    {
        id: 'power-watch',
        level: 'global',
        title: 'পাওয়ার-ওয়াচ',
        subtitle: 'লোডশেডিং ও বিদ্যুৎ খবর',
        icon: Zap,
        gradient: 'from-yellow-400 via-amber-500 to-orange-500',
        softBg: 'bg-yellow-500/12',
        ring: 'ring-yellow-500/25',
        iconTint: 'text-yellow-600',
        featured: false,
        free: true,
        href: paths.service('power-watch'),
    },
    {
        id: 'labor',
        level: 'union',
        title: 'ডিজি-শ্রমিক',
        subtitle: 'মিস্ত্রি ও কামলা ডিরেক্টরি',
        icon: Wrench,
        gradient: 'from-slate-600 via-zinc-700 to-neutral-800',
        softBg: 'bg-zinc-500/12',
        ring: 'ring-zinc-500/25',
        iconTint: 'text-zinc-600',
        featured: false,
        free: true,
        href: paths.service('labor'),
    },
    {
        id: 'agri-pool',
        level: 'union',
        title: 'এগ্রি-পুল',
        subtitle: 'কৃষি যন্ত্রপাতি ভাড়া',
        icon: Tractor,
        gradient: 'from-lime-500 via-green-600 to-emerald-700',
        softBg: 'bg-lime-500/12',
        ring: 'ring-lime-500/25',
        iconTint: 'text-lime-600',
        featured: false,
        free: true,
        href: paths.service('agri-pool'),
    },
    {
        id: 'land-guard',
        level: 'union',
        title: 'স্মার্ট ভূমি সেবা',
        subtitle: 'AI দলিল বিশ্লেষণ ও খারিজ গাইড',
        icon: ShieldAlert,
        gradient: 'from-indigo-600 via-blue-700 to-slate-800',
        softBg: 'bg-indigo-500/12',
        ring: 'ring-indigo-500/25',
        iconTint: 'text-indigo-600',
        featured: true,
        free: false,
        href: paths.service('land-guard'),
    },
    {
        id: 'more',
        level: 'global',
        title: 'আরও সেবা',
        subtitle: 'সমিতি, কৃষি ও ভবিষ্যৎ এআই',
        icon: LayoutGrid,
        gradient: 'from-slate-500 via-slate-600 to-zinc-800',
        softBg: 'bg-slate-500/10',
        ring: 'ring-slate-400/20',
        iconTint: 'text-slate-600',
        featured: false,
        free: true,
        href: paths.service('more'),
    },
];

export const FEATURED_FOR_HERO = SERVICE_CATEGORIES.filter((c) => c.featured);

export const HEADER_QUICK_LINKS = [
    SERVICE_CATEGORIES.find((c) => c.id === 'blood'),
    SERVICE_CATEGORIES.find((c) => c.id === 'emergency'),
    SERVICE_CATEGORIES.find((c) => c.id === 'e-up'),
].filter(Boolean);
